# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.

colorScheme = "ocean"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]#, "suggestions"]
# robots = ""

disableImageOptimization = true
disableTextInHeader = true

# defaultBackgroundImage = "/img/data_center_bw.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, custom
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = '/posts'
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true
  homepageImage = "/img/data_center.jpg"

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateOnlyInArticle = true
  showDateUpdated = true
  showAuthor = false
  showHero = false
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editAppendPath = true
  seriesOpened = true
  showHeadingAnchors = false
  showPagination = false
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = false
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "whatsapp", "telegram", "pinterest", "reddit", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showSummary = false
  showCards = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardViewScreenWidth = false
  cardView = false

[buymeacoffee]
  identifier = "theneuralme"
  globalWidget = true
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "Right"
